using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Zaap
{
    public class HunterRelator
    {
        public static string FetchQuery = "SELECT * FROM jobs_hunter";
    }

    [TableName("jobs_hunter")]
    public class ChasseurRecord : IAutoGeneratedRecord
    {
        [PrimaryKey("MonsterId")] public int MonsterId { get; set; }

        public int DropId { get; set; }

        public int Level { get; set; }

        public string Note { get; set; }
    }
}