using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Database.Spells.SpellFixe
{
    [TableName("spellfixer")]
    public class SpellFixer : IAutoGeneratedRecord
    {
        public int Id { get; set; }

        public int SpellId { get; set; }

        public short EffectEnumId { get; set; }

        public short Value { get; set; }

        public short Diceface { get; set; }

        public short Diceenum { get; set; }

        public short Duration { get; set; }

        public int SpellTargetTypeId { get; set; }
    }
}