using System.Collections.Generic;
using System.Linq;
using Stump.Core.IO;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Companion
{
    [TableName("companions")]
    public class CompanionRecord : IAutoGeneratedRecord
    {
        [PrimaryKey("Id")] public int Id { get; set; }

        public int ItemId { get; set; }

        public string Look { get; set; }

        public int StartingSpellLevelId { get; set; }

        [NullString] public string Characterisitcs { get; set; }

        [NullString]
        public string Spells
        {
            get => SpellsId.ToCSV(",");
            set => SpellsId = value.FromCSV<int>(",").ToList();
        }

        [NullString] public string BoneId { get; set; }

        [Ignore] public List<int> SpellsId { get; set; } = new List<int>();
    }
}