using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Items
{
    public class PlayerMerchantItemRelator
    {
        public static string FetchQuery = "SELECT * FROM characters_items_selled";

        /// <summary>
        ///     Use string.Format
        /// </summary>
        public static string FetchByOwner = "SELECT * FROM characters_items_selled WHERE OwnerId={0}";
    }

    [TableName("characters_items_selled")]
    public class PlayerMerchantItemRecord : ItemRecord<PlayerMerchantItemRecord>, IAutoGeneratedRecord
    {
        private int m_ownerId;

        private long m_price;

        private uint m_stackSold;

        [Index]
        public int OwnerId
        {
            get => m_ownerId;
            set
            {
                m_ownerId = value;
                IsDirty = true;
            }
        }

        public long Price
        {
            get => m_price;
            set
            {
                m_price = value;
                IsDirty = true;
            }
        }

        public uint StackSold
        {
            get => m_stackSold;
            set
            {
                m_stackSold = value;
                IsDirty = true;
            }
        }
    }
}