using Stump.DofusProtocol.Enums;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Items
{
    public class PlayerItemRelator
    {
        public static string FetchQuery = "SELECT * FROM characters_items";

        /// <summary>
        ///     Use string.Format
        /// </summary>
        public static string FetchByOwner = "SELECT * FROM characters_items WHERE OwnerId={0}";
    }

    [TableName("characters_items")]
    public class PlayerItemRecord : ItemRecord<PlayerItemRecord>, IAutoGeneratedRecord
    {
        private int m_ownerId;

        private CharacterInventoryPositionEnum m_position;

        [Index]
        public int OwnerId
        {
            get => m_ownerId;
            set
            {
                m_ownerId = value;
                IsDirty = true;
            }
        }

        public CharacterInventoryPositionEnum Position
        {
            get => m_position;
            set
            {
                m_position = value;
                IsDirty = true;
            }
        }

        public bool IsExo { get; set; }

        public bool IsExoPa { get; set; }

        public bool IsExoPm { get; set; }

        public bool IsExoPo { get; set; }

        public bool IsExoInvoc { get; set; }
    }
}