using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Monsters
{
    [TableName("monsters_agression_honors")]
    public class MonsterAgressionRecord : IAutoGeneratedRecord
    {
        public int Id { get; set; }

        public int MonsterId { get; set; }

        public int SubAreaId { get; set; }

        public int AlignmentId { get; set; }

        public int HonorId { get; set; }
    }

    public class MonsterAgressionRelator
    {
        public static string FetchQuery = "SELECT * FROM monsters_agression_honors";
    }
}