using System.Collections.Generic;
using System.Linq;
using Stump.Core.IO;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Game.Maps;

namespace Stump.Server.WorldServer.Database.Monsters
{
    public class MonsterNaniRelator
    {
        public static string FetchQuery = "SELECT * FROM monsters_nani";
    }

    [TableName("monsters_nani")]
    public class MonsterNaniRecord : IAutoGeneratedRecord
    {
        public int Id { get; set; }

        public int MonsterGradeId { get; set; }

        public string SubAreasCSV { get; set; }

        [Ignore]
        public SubArea[] SubAreas
        {
            get
            {
                var list = new List<SubArea>();
                foreach (var id in SubAreasCSV.FromCSV<int>(";"))
                {
                    var subarea = Game.World.Instance.GetSubArea(id);
                    if (subarea != null) list.Add(subarea);
                }

                return list.ToArray();
            }
            set { SubAreasCSV = value.Select(x => x.Id).ToCSV(";"); }
        }
    }
}