using Stump.DofusProtocol.Types;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.HavenBags
{
    public class HavenBagFurnitureRelator
    {
        public static string FetchQuery = "SELECT * FROM havenbags_furnitures";
    }

    [TableName("havenbags_furnitures")]
    public class HavenBagFurnitureRecord : IAutoGeneratedRecord
    {
        [Index] [PrimaryKey("Id")] public int Id { get; set; }


        public int HavenBagId { get; set; }

        public int FurnitureId { get; set; }

        public ushort CellId { get; set; }

        public sbyte Orientation { get; set; }

        [Ignore]
        public HavenBagFurnitureInformation HavenBagFurnitureInformation
        {
            get => new HavenBagFurnitureInformation(CellId, FurnitureId, Orientation);
            set
            {
                FurnitureId = value.FunitureId;
                CellId = value.CellId;
                Orientation = value.Orientation;
            }
        }
    }
}