using Stump.DofusProtocol.D2oClasses;
using Stump.DofusProtocol.D2oClasses.Tools.D2o;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.HavenBags
{
    public class HavenBagThemesRelator
    {
        public static string FetchQuery = "SELECT * FROM havenbags_themes";
    }

    [TableName("havenbags_themes")]
    [D2OClass("HavenbagTheme", "com.ankamagames.dofus.datacenter.houses")]
    public class HavenBagThemes : IAssignedByD2O, IAutoGeneratedRecord
    {
        [PrimaryKey("Id", false)] public int Id { get; set; }

        public int MapId { get; set; }

        public int CellId { get; set; }

        public int NameId { get; set; }

        public void AssignFields(object d2oObject)
        {
            var havenbagtheme = (HavenbagTheme) d2oObject;
            Id = havenbagtheme.Id;
            MapId = (int) havenbagtheme.MapId;
            NameId = havenbagtheme.NameId;
        }
    }
}