using Stump.DofusProtocol.D2oClasses.Classes.misc;
using Stump.DofusProtocol.D2oClasses.Tools.D2o;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Misc
{
    public class BreachPrizeRelator
    {
        public const string FetchQuery = "SELECT * FROM breach_prizes";
    }

    [TableName("breach_prizes")]
    [D2OClass("BreachPrize", "com.ankamagames.dofus.datacenter.misc")]
    public class BreachPrizeRecord : IAssignedByD2O, ISaveIntercepter, IAutoGeneratedRecord
    {
        [PrimaryKey("Id")] public int Id { get; set; }


        public uint NameId { get; set; }


        public int Currency { get; set; }


        public string TooltipKey { get; set; }

        public uint DescriptionKey { get; set; }

        public int CategoryId { get; set; }

        [D2OIgnore] public int ItemId { get; set; }

        public virtual void AssignFields(object obj)
        {
            var castedObj = (BreachPrize) obj;

            Id = castedObj.id;
            NameId = castedObj.nameId;
            Currency = castedObj.currency;
            TooltipKey = castedObj.tooltipKey;
            DescriptionKey = castedObj.descriptionKey;
            CategoryId = castedObj.categoryId;
            ItemId = castedObj.itemId;
        }

        public void BeforeSave(bool insert)
        {
        }
    }
}