using Stump.Core.IO;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Misc
{
    public class BreachBossRelator
    {
        public const string FetchQuery = "SELECT * FROM breach_bosses";
    }

    [TableName("breach_bosses")]
    public class BreachBossRecord : IAutoGeneratedRecord
    {
        private int[] m_incompatibleBosses;
        private string m_incompatibleBossesCSV;

        [PrimaryKey("Id", false)] public int Id { get; set; }


        public int MonsterId { get; set; }


        public int Category { get; set; }


        public string ApparitionCriterion { get; set; }


        public string AccessCriterion { get; set; }

        public int MaxRewardQuantity { get; set; }

        public int[] IncompatibleBosses
        {
            get => m_incompatibleBosses;
            set
            {
                m_incompatibleBosses = value;
                m_incompatibleBossesCSV = value.ToCSV(",");
            }
        }

        public string IncompatibleBossesCSV
        {
            get => m_incompatibleBossesCSV;
            set
            {
                m_incompatibleBossesCSV = value;
                m_incompatibleBosses = value.FromCSV<int>(",");
            }
        }

        public uint RewardId { get; set; }
    }
}